[sdxl_arguments]
cache_text_encoder_outputs = false
no_half_vae = true
min_timestep = 0
max_timestep = 1000
shuffle_caption = false

[model_arguments]
pretrained_model_name_or_path = "/cognitive_comp/wuxiaojun/pretrained/Taiyi-Stable-Diffusion-XL-3.5B/taiyi_diffusion_xl.safetensors"
taiyi = true


[dataset_arguments]
debug_dataset = false
in_json = "/cognitive_comp/wuxiaojun/IDEA-CCNL/taiyi-diffusion-xl/data/catwomen_data/json/meta_lat.json"
train_data_dir = "/cognitive_comp/wuxiaojun/IDEA-CCNL/taiyi-diffusion-xl/data/catwomen_data"
latents_data_dir="/cognitive_comp/wuxiaojun/IDEA-CCNL/taiyi-diffusion-xl/data/catwomen_data_latents_1024"
dataset_repeats = 10
keep_tokens = 0
resolution = "1024,1024"
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
color_aug = false
token_warmup_min = 1
token_warmup_step = 0

[training_arguments]
output_dir = "./outputs/catwoman_1024"
output_name = "catwoman_1024"
save_precision = "fp16"
save_every_n_epochs = 1
# save_state = true
train_batch_size = 2
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 100
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "bf16"

[logging_arguments]
log_with = "wandb"
logging_dir = "./logs"
log_prefix = "catwoman_1024"

[sample_prompt_arguments]
sample_every_n_epochs = 1
sample_sampler = "euler_a"

[saving_arguments]
save_model_as = "safetensors"

[optimizer_arguments]
optimizer_type = "AdaFactor"
learning_rate = 1e-6
train_text_encoder = true
text_encoder_lr=1e-6
max_grad_norm = 0
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False",]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 100

[advanced_training_config]
